time mpirun -np 1 -use-hwthread-cpus -oversubscribe  ./q1  < in.txt > out.txt  
time mpirun -np 2 -use-hwthread-cpus -oversubscribe  ./q1  < in.txt >> out.txt 
time mpirun -np 3 -use-hwthread-cpus -oversubscribe  ./q1  < in.txt >> out.txt 
time mpirun -np 4 -use-hwthread-cpus -oversubscribe  ./q1   < in.txt >> out.txt 
time mpirun -np 5 -use-hwthread-cpus -oversubscribe  ./q1  < in.txt >> out.txt 
time mpirun -np 6 -use-hwthread-cpus -oversubscribe  ./q1  < in.txt >> out.txt 
time mpirun -np 7 -use-hwthread-cpus -oversubscribe  ./q1 < in.txt >> out.txt 
time mpirun -np 8 -use-hwthread-cpus -oversubscribe  ./q1  < in.txt >> out.txt 
time mpirun -np 9 -use-hwthread-cpus -oversubscribe  ./q1  < in.txt >> out.txt 
time mpirun -np 10 -use-hwthread-cpus -oversubscribe  ./q1  < in.txt >> out.txt 
time mpirun -np 11 -use-hwthread-cpus -oversubscribe  ./q1  < in.txt >> out.txt 
time mpirun -np 12 -use-hwthread-cpus -oversubscribe  ./q1  < in.txt >> out.t